# Generated by Django 2.0.5 on 2018-05-26 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_mod_time',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='last_mod_time',
        ),
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=1, verbose_name='标签数目'),
        ),
        migrations.AddField(
            model_name='tag',
            name='number',
            field=models.IntegerField(default=1, verbose_name='标签数目'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
