# Generated by Django 2.0.5 on 2018-05-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180527_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='number',
        ),
    ]
