# Generated by Django 2.0.5 on 2018-05-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['body'], 'verbose_name': '评论', 'verbose_name_plural': '评论列表'},
        ),
        migrations.AlterModelTable(
            name='articlecomment',
            table='comment',
        ),
    ]
