# Generated by Django 2.0.5 on 2018-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180528_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='username',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
