# Generated by Django 2.0.5 on 2018-05-28 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180529_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_time', 'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_mod_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
        ),
    ]
