# Generated by Django 2.0.5 on 2018-05-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180529_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='nickname',
            field=models.CharField(default='匿名', max_length=50),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
