# Generated by Django 2.0.5 on 2018-05-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180529_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['-createtime'], 'verbose_name': '评论', 'verbose_name_plural': '评论列表'},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
