# Generated by Django 2.0.5 on 2018-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180529_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
    ]
