# Generated by Django 2.0.5 on 2018-05-29 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_user_comment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
