# Generated by Django 2.0.5 on 2018-05-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180529_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_time',
        ),
    ]
