# Generated by Django 2.0.5 on 2018-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.CharField(default=1, max_length=100, verbose_name='标号'),
            preserve_default=False,
        ),
    ]
